# Generated by Django 2.0 on 2017-12-03 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('CodCliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Cpf', models.CharField(max_length=11)),
                ('Email', models.EmailField(blank=True, max_length=100)),
                ('DataNascimento', models.DateField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0))),
                ('DataCadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('CodEndereco', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Logradouro', models.CharField(max_length=250)),
                ('Numero', models.CharField(max_length=10)),
                ('Complemento', models.CharField(max_length=250)),
                ('Bairro', models.CharField(max_length=100)),
                ('Cep', models.CharField(max_length=8)),
                ('Cidade', models.CharField(max_length=70)),
                ('Estado', models.CharField(max_length=70)),
                ('Ativo', models.BooleanField(default=True)),
                ('CodCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filiacao.Cliente')),
            ],
        ),
    ]
