# Generated by Django 2.0 on 2017-12-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filiacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='DataNascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
